apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: default
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
  - name: http
    port: 8080
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: default
  labels:
    app: payment
spec:
  selector:
    app: payment
  ports:
  - name: http
    port: 8080
    targetPort: 8080
